version: "3.9"

services:
  boudypilot:
    build: .
    ports:
      - "8501:8501"
    environment:
      MISTRAL_API_KEY: YOUR KEEEEYYY :)
      TAVILY_API_KEY: YOUR KEEEEYYY :)
      SENDGRID_API_KEY: YOUR KEEEEYYY :)
      FROM_EMAIL: YOUR MAIL :)
    volumes:
      - ./:/app

